services:
    core.type_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle\Entity\Type']

    core.configuration_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle\Entity\Configuration']

    core.measure_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle\Entity\Measure']

    core.alert_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle\Entity\Alert']
