imports:
    - { resource: repository.yml }
    - { resource: filter.yml }
    - { resource: voter.yml }
    - { resource: notification.yml }

services:
    core.trigger_alert:
        class: CoreBundle\Service\TriggerAlert
        arguments: ['@doctrine', '@event_dispatcher']

    core.event_subscriber:
        class: CoreBundle\EventSubscriber\EventSubscriber
        arguments: ['@core.trigger_alert', '@core.send_notification']
        tags:
            - { name: kernel.event_subscriber }

    core.history_notification_handler:
        class: CoreBundle\Service\HistoryNotificationHandler
        arguments: ['@core.history_notification_repository']
